let demoBoardSetup = [
    [{audio: new Audio('../src/sounds/bass/c.mp3'), classList:["c tile"], emoji:"🍊"},{audio: new Audio('../src/sounds/bells/cc.mp3'), classList:["cc tile"], emoji:"🍇"},{audio: new Audio('../src/sounds/synth/cc.mp3'), classList:["cc tile"], emoji:"🍓"},{audio: new Audio('../src/sounds/piano/e.mp3'), classList:["e tile"], emoji:"🍍"},{audio: new Audio('../src/sounds/trombone/c.mp3'), classList:["c tile"], emoji:"🍌"},{audio: new Audio('../src/sounds/drums/cc.mp3'), classList:["cc tile"], emoji:"🥥"}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/guitar/g.mp3'), classList:["g tile"], emoji:"🍎"},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/marimba/g.mp3'), classList:["g tile"], emoji:"🍉"},{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/marimba/cc.mp3'), classList:["cc tile"], emoji:"🍉"},{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/drums/cc.mp3'), classList:["cc tile"], emoji:"🥥"}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/drums/b.mp3'), classList:["b tile"], emoji:"🥥"},{audio: new Audio('../src/sounds/drums/cc.mp3'), classList:["cc tile"], emoji:"🥥"}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/guitar/a.mp3'), classList:["a tile"], emoji:"🍎"},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""}],
    [{audio: new Audio('../src/sounds/bass/g.mp3'), classList:["g tile"], emoji:"🍊"},{audio: new Audio('../src/sounds/marimba/f.mp3'), classList:["f tile"], emoji:"🍉"},{audio: new Audio('../src/sounds/bells/g.mp3'), classList:["g tile"], emoji:"🍇"},{audio: new Audio('../src/sounds/trombone/e.mp3'), classList:["e tile"], emoji:"🍌"},{audio: new Audio('../src/sounds/synth/d.mp3'), classList:["d tile"], emoji:"🍓"},{audio: new Audio('../src/sounds/marimba/a.mp3'), classList:["a tile"], emoji:"🍉"}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""}],
    [{audio: new Audio('../src/sounds/marimba/g.mp3'), classList:["g tile"], emoji:"🍉"},{audio: new Audio('../src/sounds/marimba/e.mp3'), classList:["e tile"], emoji:"🍉"},{audio: new Audio('../src/sounds/guitar/g.mp3'), classList:["g tile"], emoji:"🍎"},{audio: new Audio('../src/sounds/synth/e.mp3'), classList:["e tile"], emoji:"🍓"},{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/drums/cc.mp3'), classList:["cc tile"], emoji:"🥥"}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/guitar/cc.mp3'), classList:["cc tile"], emoji:"🍎"},{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/guitar/c.mp3'), classList:["c tile"], emoji:"🍎"},{audio: null, classList:["empty tile"], emoji:""}],
    [{audio: new Audio('../src/sounds/bass/e.mp3'), classList:["e tile"], emoji:"🍊"},{audio: new Audio('../src/sounds/trombone/g.mp3'), classList:["g tile"], emoji:"🍌"},{audio: new Audio('../src/sounds/drums/g.mp3'), classList:["g tile"], emoji:"🥥"},{audio: new Audio('../src/sounds/drums/b.mp3'), classList:["b tile"], emoji:"🥥"},{audio: new Audio('../src/sounds/drums/e.mp3'), classList:["e tile"], emoji:"🥥"},{audio: new Audio('../src/sounds/drums/cc.mp3'), classList:["cc tile"], emoji:"🥥"}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: new Audio('../src/sounds/bells/b.mp3'), classList:["b tile"], emoji:"🍇"},{audio: new Audio('../src/sounds/synth/g.mp3'), classList:["g tile"], emoji:"🍓"},{audio: new Audio('../src/sounds/piano/f.mp3'), classList:["f tile"], emoji:"🍍"},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""}],
    [{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""},{audio: null, classList:["empty tile"], emoji:""}]
]

export default demoBoardSetup